# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/tts/v1/tts.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api/tts/v1/tts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61pi/tts/v1/tts.proto\x12\x06tts.v1\"m\n\x11SynthesizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05voice\x18\x02 \x01(\t\x12\x16\n\x0esample_rate_hz\x18\x03 \x01(\x05\x12\x14\n\x0c\x61udio_format\x18\x04 \x01(\t\x12\r\n\x05speed\x18\x05 \x01(\x02\"\x1b\n\nAudioChunk\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\"G\n\x05Voice\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tlang_code\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\t\x12\x0f\n\x07\x64isplay\x18\x04 \x01(\t\"\'\n\x05\x41lias\x12\r\n\x05\x61lias\x18\x01 \x01(\t\x12\x0f\n\x07maps_to\x18\x02 \x01(\t\"\x13\n\x11ListVoicesRequest\"S\n\x12ListVoicesResponse\x12\x1d\n\x06voices\x18\x01 \x03(\x0b\x32\r.tts.v1.Voice\x12\x1e\n\x07\x61liases\x18\x02 \x03(\x0b\x32\r.tts.v1.Alias2\x89\x01\n\x03TTS\x12=\n\nSynthesize\x12\x19.tts.v1.SynthesizeRequest\x1a\x12.tts.v1.AudioChunk0\x01\x12\x43\n\nListVoices\x12\x19.tts.v1.ListVoicesRequest\x1a\x1a.tts.v1.ListVoicesResponseB/Z-github.com/vjovkovs/GoParser/api/tts/v1;ttsv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.tts.v1.tts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z-github.com/vjovkovs/GoParser/api/tts/v1;ttsv1'
  _globals['_SYNTHESIZEREQUEST']._serialized_start=32
  _globals['_SYNTHESIZEREQUEST']._serialized_end=141
  _globals['_AUDIOCHUNK']._serialized_start=143
  _globals['_AUDIOCHUNK']._serialized_end=170
  _globals['_VOICE']._serialized_start=172
  _globals['_VOICE']._serialized_end=243
  _globals['_ALIAS']._serialized_start=245
  _globals['_ALIAS']._serialized_end=284
  _globals['_LISTVOICESREQUEST']._serialized_start=286
  _globals['_LISTVOICESREQUEST']._serialized_end=305
  _globals['_LISTVOICESRESPONSE']._serialized_start=307
  _globals['_LISTVOICESRESPONSE']._serialized_end=390
  _globals['_TTS']._serialized_start=393
  _globals['_TTS']._serialized_end=530
# @@protoc_insertion_point(module_scope)
