# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api.tts.v1 import tts_pb2 as api_dot_tts_dot_v1_dot_tts__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in api/tts/v1/tts_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TTSStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Synthesize = channel.unary_stream(
                '/tts.v1.TTS/Synthesize',
                request_serializer=api_dot_tts_dot_v1_dot_tts__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=api_dot_tts_dot_v1_dot_tts__pb2.AudioChunk.FromString,
                _registered_method=True)
        self.ListVoices = channel.unary_unary(
                '/tts.v1.TTS/ListVoices',
                request_serializer=api_dot_tts_dot_v1_dot_tts__pb2.ListVoicesRequest.SerializeToString,
                response_deserializer=api_dot_tts_dot_v1_dot_tts__pb2.ListVoicesResponse.FromString,
                _registered_method=True)


class TTSServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Synthesize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVoices(self, request, context):
        """NEW
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TTSServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Synthesize': grpc.unary_stream_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=api_dot_tts_dot_v1_dot_tts__pb2.SynthesizeRequest.FromString,
                    response_serializer=api_dot_tts_dot_v1_dot_tts__pb2.AudioChunk.SerializeToString,
            ),
            'ListVoices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVoices,
                    request_deserializer=api_dot_tts_dot_v1_dot_tts__pb2.ListVoicesRequest.FromString,
                    response_serializer=api_dot_tts_dot_v1_dot_tts__pb2.ListVoicesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tts.v1.TTS', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tts.v1.TTS', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TTS(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tts.v1.TTS/Synthesize',
            api_dot_tts_dot_v1_dot_tts__pb2.SynthesizeRequest.SerializeToString,
            api_dot_tts_dot_v1_dot_tts__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tts.v1.TTS/ListVoices',
            api_dot_tts_dot_v1_dot_tts__pb2.ListVoicesRequest.SerializeToString,
            api_dot_tts_dot_v1_dot_tts__pb2.ListVoicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
