name: Kokoro CLI TTS (from Crawl)

on:
  workflow_run:
    workflows: ["Crawl"]        # 👈 must match the name of your crawl workflow
    types: [completed]

jobs:
  tts:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      KOKORO_REPO_ID: "hexgrad/Kokoro-82M"
      PYTHONWARNINGS: "ignore:dropout option adds dropout,ignore::FutureWarning"
      # Adjust if your Crawl writes elsewhere; commonly it uploads "out/**"
      CRAWL_ARTIFACT_NAME: "crawl-output-${{ github.event.workflow_run.id }}"
      INPUT_DIR: "crawl_out/out/chapters"      # 👈 where TXT chapters live inside the artifact
      SUMMARY_PATH: "out/audio/summary.json"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Download the artifact produced by the triggering Crawl run
      - name: Download crawl artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.CRAWL_ARTIFACT_NAME }}
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          path: crawl_out

      - name: Show crawled files
        run: ls -R ./crawl_out || true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: server_py/requirements.txt

      - name: Cache Hugging Face models
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface
          key: hf-${{ runner.os }}-${{ env.KOKORO_REPO_ID }}
          restore-keys: |
            hf-${{ runner.os }}-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r server_py/requirements.txt

      - name: (Optional) Install ffmpeg for MP3
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: List voices
        run: python server_py/kokoro_cli.py list --catalog voices/voices.json

      - name: Run TTS over crawled chapters
        run: |
          if [ ! -d "${{ env.INPUT_DIR }}" ]; then
            echo "::error::No chapters dir at ${{ env.INPUT_DIR }}. Check your Crawl artifact paths."
            exit 1
          fi
          python server_py/kokoro_cli.py synth \
            --input "${{ env.INPUT_DIR }}" \
            --out "out/audio" \
            --voice "af_heart" \
            --rate 24000 \
            --speed 1.0 \
            --final mp3 \
            --recursive \
            --summary-json "${{ env.SUMMARY_PATH }}" \
            --progress auto --verbose

          if [ -f "${{ env.SUMMARY_PATH }}" ]; then
            echo "------- summary.json -------"
            cat "${{ env.SUMMARY_PATH }}" || true
            echo "----------------------------"
          fi

      - name: Upload audio (and summary)
        uses: actions/upload-artifact@v4
        with:
          name: kokoro-audio-${{ github.run_id }}
          path: |
            out/audio/**
          if-no-files-found: error
